- addon/listeners/key-events.js
`Array.prototype.includes()` does not get transpiled by babel and is not available in the vast majority of browsers yet. This PR uses the ES5 equivalent of containment checking instead.
> legacy browser support

- tests/dummy/app/templates/index.hbs
Add note to docs that EKMixin must be used as well as any "common pattern" mixins
While this could be determined by a simple look at the actual mixin code, I feel like a quick note like this might be helpful, and would have saved me 5 minutes or so of confusion :smile:
> Add note to demo documentation regarding common pattern mixins

- addon/listeners/key-events.js
- addon/utils/get-cmd-key.js
- addon/utils/handle-key-event.js
- addon/utils/listener-name.js
- app/utils/get-cmd-key.js
- tests/dummy/app/templates/usage.hbs
- tests/unit/utils/get-cmd-key-test.js
- tests/unit/utils/listener-name-test.js
Users of macOS expect to press Command+Key whereas Windows, Linux, etc.
expect to press Ctrl+Key. This allows easily defining that behavior.
Fixes #38.
> Allow using `cmd` as DSL for ctrl or command key.

- addon/services/keyboard.js
- tests/unit/services/keyboard-test.js
This PR fixes an issue with unregistering event listeners.  This is a pretty minor bug with respect to production code, but can lead to some pretty severe memory leaks in a testing environment. Lingering listeners tend to retain a fairly large chunk of memory through their own references to things.
To fix this issue, we just switch from using [`isDestroying`](http://emberjs.com/api/classes/Ember.Service.html#property_isDestroying) to [`willDestroy`](http://emberjs.com/api/classes/Ember.Service.html#method_willDestroy)
I also added an additional test that calls `service.destroy` from within the Ember run loop to verify that `willDestroy` gets called properly.
> Fix a bug with unregistering jquery listeners

- addon/utils/get-cmd-key.js
A simple fix for an error occurring in fastboot.
> Bugfix in utils/get-cmd-key: problem with fastboot

- ember-cli-build.js
Was accidentally removed in 8ed8fe7354df2e3061d642b0a5bf252360f4226a
> docs: fix syntax highlighting

- addon/services/keyboard.js
- addon/utils/handle-key-event.js
- tests/acceptance/ember-keyboard-test.js
- tests/dummy/app/components/key-down-counter.js
- tests/dummy/app/components/keyboard-propagation-widget.js
- tests/dummy/app/templates/components/key-down-counter.hbs
- tests/dummy/app/templates/components/keyboard-propagation-widget.hbs
- tests/dummy/app/templates/priority.hbs
- tests/dummy/app/templates/test-scenario.hbs
Closes #63.
While working on this I've realized that `keyboardLaxPriority` is fundamentally incompatible with `stopPropagation`, since the latter expects events to 'bubble' by default. Therefore user have to opt in to the new semantics by setting `emberKeyboard.propagate` to `true` in their config. This option can also be set at run time on the `keyboard` service as `isPropagationEnabled`.
Only if `isPropagationEnabled` is `true`, the second `ekEvent` argument is passed to the event listeners.
The semantics are explained in the docs, but for easier access, I'll quote them here:
> By setting `emberKeyboard.propagate` in the `config/environment.js` to `true`,
> you're opting into the new event propagation semantics that were introduced in
> [issue …
> Event propagation

- addon/index.js
- addon/mixins/activate-keyboard-on-init.js
- tests/dummy/app/templates/mixins.hbs
This reduces boilerplate just like onInsert and the other helper mixins. Just this time for controllers. Controllers aren't dead, long live controllers.
> Adds onInit mixin for use in controllers.

- tests/unit/services/keyboard-test.js
- Prior to this fix, any click or key press at the end of a test run would throw an error.
> Fix an issue in the keyboard service unit test that left key responders registered

- ember-cli-build.js
- package.json
- tests/dummy/app/styles/dummy.css
- tests/dummy/app/templates/index.hbs
- tests/dummy/app/templates/mixins.hbs
- tests/dummy/app/templates/usage.hbs
- yarn.lock
after on the left, before on the right:
Fixes #176
> Improve readability of docs site

- addon/utils/keyboard-listener.js
- tests/unit/utils/is-key-test.js
This adds support for binding to the `+` via just (if using decorators):
```
@onKey("+")
```
I'm not entirely sure how this would work with different language keyboard layouts tbh…
closes #280
> support binding to "+" key

- addon/services/keyboard.js
- tests/dummy/app/templates/deprecations.hbs
Closes #164.
Should be released as v6.0.4
Part of #116.
> Deprecate old propagation model

- config/ember-try.js
- package.json
- yarn.lock
This fixes deprecations in recent version of Ember and add support for Ember v4
> Update ember-modifier to add support for 3.22 modifier capabilities

- tests/dummy/app/helpers/format-markdown.js
Noticed in `embroider-optimized` scenario output:
```
WARNING in ./helpers/format-markdown.js 14:2-19
export 'default' (imported as 'marked') was not found in 'marked' (possible exports: Lexer, Parser, Renderer, Slugger, TextRenderer, Tokenizer, defaults, getDefaults, lexer, marked, options, parse, parseInline, parser, setOptions, use, walkTokens)
@ ./templates/deprecations.hbs 1:0-47 3:9-11
@ ./assets/dummy.js 78:9-49
```
followed recomendation from https://marked.js.org/#usage
> Fix marked import in format-markdown helper

- addon/modifiers/on-key.js
- package.json
- tests/acceptance/on-key-modifier-test.js
- yarn.lock
As we explicitly set Ember 3.8 as minimal supported version, there does not seem a need to error about the same and addon can have one less dependency.
> Move ember-compatibility-helpers to devDependencies

- addon-test-support/key-event.js
- addon-test-support/test-helpers.js
- addon/services/keyboard.js
- tests/acceptance/disable-on-input-fields-config-test.js
- tests/dummy/app/app.js
- tests/dummy/app/custom-elements/input-in-open-shadow.js
- tests/dummy/app/templates/test-scenario/index.hbs
I tried #557 with the new release, but it failed for us due to a special circumstance in our particular app: we embed it into a 3rd party pages, and for better encapsulation we wrap the whole app inside a shadow DOM. 
This however comes with some side effects, also encountered in other places, especially due to the way events are handled across shadow boundaries: when the key event traverses the shadow root, its `event.target` is not anymore the (input) element the event originated from, but the shadow root (to "hide" the internals of the shadow DOM for the outer DOM). So now it's tagName is *not* `INPUT` anymore, breaking the input/textarea detection.
> ℹ️ Here is a good explanation of events and shadow DOM, if someone is interested: …
> Support inputs in shadow DOM in disableOnInputFields mode

- addon/CHANGELOG.md
Highlight.js has already been upgraded to a recent version: https://github.com/adopted-ember-addons/ember-keyboard/blob/e95d348455dc49b6b9812ac12a31fbf775b0b73e/yarn.lock#L7238-L7246 Let's remove the annoying warning as well from changelog.
While doing so I noticed that the changelog does not have a title yet. I added one.
> replace highlight.js EOL warning in changelog by title

- addon/src/modifiers/on-key.js
- test-app/config/ember-try.js
- test-app/package.json
- yarn.lock
This is fix for the logic/condition introduced in #617
Condition about whether to use new or old version of `on-key` modifier class was flipped.
Additionally, this adds `useWorkspaces` to ember-try config
so that proper version of `ember-modifier` is used
across the monorepo.
This is needed so that `ember-modifier-X` ember-try scenarios
resolve to the same version of `ember-modifier` both in the
`test-app` and `addon` workspaces.
`ember-classic` scenario should not use `useWorkspaces` flag as only test-app need to get classic flags.
> Fix ember-modifier v3.2 compatibility

- docs/app/templates/usage.hbs
I was getting errors using `import { isKey } from 'ember-keyboard';` and the code seems to use `import isKey from 'ember-keyboard/utils/is-key';`.
> Fix `isKey` import in documentation usage

- addon/src/decorators/key-responder.js
I am getting deprecations thrown from willDestroy from keyResponder used on an ember-modifier class-based modifier.
I think this change fixes things for everyone, and no more deprecations!
> Make keyResponder ember-modifier@4 compat

- docs/package.json
- test-app/package.json
- yarn.lock
PR https://github.com/emberjs/ember-test-helpers/pull/1211 (released in v2.8.0)
made `ember-source` a peerDependency of `@ember/test-helpers`.
In case of `ember-keyboard` monorepo setup, package `ember-source`
does not get hoisted and stay in the `test-app/node_modules` but at the same time
`@ember/test-helpers` gets hoisted as well as some another version of `ember-source`.
By pinning `@ember/test-helpers` package we avoid this issue.
> pin @ember/test-helpers to 2.6.0

- .github/dependabot.yml
idea is that it can make one PR at a time for all the packages within monorepo
> simplify dependabot config

- addon/package.json
@ember/test-helpers v3 has been released: https://github.com/emberjs/ember-test-helpers/releases/tag/v3.0.0
The `triggerEvent` function used in ember-keyboard is still here, so relaxing the dependencies to allow the v3 is okay.
> Allow @ember/test-helpers v3 in peer dependencies

- test-app/package.json
I digged why ember 5 tests were failing. ember-export-application-global was installed but is now deprecated and doesn't seems to be necessary to run tests.
There is one more test failing related to fastboot.
> Remove test dependency ember-export-application-global that break most ember 5 tests

- addon/src/utils/keyboard-listener.js
- test-app/app/controllers/test-scenario/on-key-helper-examples.js
- test-app/app/templates/test-scenario/on-key-helper-examples.hbs
- test-app/tests/acceptance/on-key-helper-test.js
Ember-keyboard currently does not support key combos that contain a plus sign and modifier keys, e.g. shift++ and ctrl++.
Also, the colon usage was being achieved through a split/join, but it could be replaced by regex match.
Adds support for the plus sign in any configuration and uses regex matching to separate the eventType from the keyCombo.
No changes are needed, since all previously supported features still work the same way.
The plus sign support could be achieved with a regex split, but it requires lookbehind, which has support conflict with Ember 3.8 and IE.
For that reason, the solution involves splitting by the plus sign and collapsing two subsequent empty strings into a plus sign.
Example: `'Ctrl++'` > `['Ctrl', '', '']` > `['Ctrl', '+']`
Regex with lookbehind: …
> Feature: Plus sign support

- addon/src/decorators/key-responder.js
- test-app/app/components/decorator-example3/component.js
When working with classic properties, ember-keyboard crawls all properties to look for handlers. However, this would evaluate computed properties which is something we should avoid.
> Don't evaluate getters when looking for handlers

- addon/src/decorators/key-responder.js
- addon/src/helpers/on-key.js
- addon/src/modifiers/on-key.js
- docs/app/components/keyboard-propagation-widget.js
- docs/app/mixins/enterable.js
I recently upgraded to ember 6.3. With the new deprecation on importing as `{ inject as service }`. See: 
https://deprecations.emberjs.com/id/importing-inject-from-ember-service
I replaced the import statements by the new correct imports.
> Fix ember deprecation of inject as service
